services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}_mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - .mongodb:/data/db

  mongo-gui:
    container_name: ${COMPOSE_PROJECT_NAME}_mongo_gui
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - 8090:8081
    depends_on:
      - mongodb
